import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Table from '../components/Table';
import Surface from '../components/Surface';

export default function Home({ data }) {
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Time Logger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Table /> */}
        <Surface />
      </main>
    </div>
  )
}


export async function getServerSideProps() {
  const data = [
    {
      start: new Date().toDateString(),
      end: new Date().toDateString(),
      user: 'shamin'
    },
    {
      start: new Date().toDateString(),
      end: new Date().toDateString(),
      user: 'kazi'
    },
    {
      start: new Date().toDateString(),
      end: new Date().toDateString(),
      user: 'inti'
    }
  ];

  return {
    props: {
      data
    }
  }
}
